### ISSUE TITLE
Your code is missing Google and Github Login which would enhance the user experience...

### ISSUE THREAD

**Issue by DhruvWebDev** [piyush-eon/url-shortener#6]
Description:

Currently, our application lacks social authentication options for Google and GitHub, which are popular among users. Implementing these login features would streamline the sign-up and login processes, making it easier for users to access the application without the need to create new credentials.

Benefits of Adding Google and GitHub Login:
Improved User Experience: Users can log in quickly using their existing accounts, reducing friction during the onboarding process.
Increased User Adoption: Simplifying the login process can lead to higher conversion rates as users are more likely to sign up if they can use their social accounts.
Enhanced Security: Leveraging established authentication methods can reduce the risk of account takeovers and enhance overall security.
User Trust: Well-known login options like Google and GitHub can increase user trust in the application.

**Comment by piyush-eon** [comment]
You can easily enable it through supabase
