### ISSUE TITLE
In your Readme.md add how to start your projects locally add steps, So that devs dont find it difficult to use your code locally....

### ISSUE THREAD

**Issue by DhruvWebDev** [piyush-eon/url-shortener#7]
Here's a concise description you can use to create an issue for adding setup instructions to the README.md file:

Description:
The README.md file currently lacks comprehensive instructions on how to start the project locally. Adding detailed steps will help developers easily set up and run the project on their machines, facilitating contributions and improving overall usability.

Proposed Steps to Include:
Prerequisites: List required software and tools (e.g., Node.js, Git).
Clone the Repository: Provide the command to clone the repo.
Navigate to Project Directory: Instructions to change into the project folder.
Install Dependencies: Command to install necessary packages.
Start the Development Server: Command to launch the server.
Access the Application: URL to access the app in the browser.
Additional Configuration: Any extra setup steps if applicable.
Adding this information will enhance the onboarding experience for new contributors and reduce potential setup-related issues

**Comment by piyush-eon** [comment]
Just watch the YT tutorial. How hard is it?

**Comment by DhruvWebDev** [comment]
But it is more accessible directly using readme

**Comment by piyush-eon** [comment]
It's alright. Its just a tutorial, not a live project.
